package mosaik.docs

import kotlinx.html.*
import kotlinx.html.stream.appendHTML
import mosaik.ui.components.Size
import mosaik.ui.components.mMenu
import mosaik.ui.components.mMenuItem
import mosaik.ui.components.mMenuTitle
import mosaik.ui.components.mSelect

/**
 * The theme the server renders before any client-side preference is applied. The
 * [themeSwitcher] (and the restore script) override `data-theme` on `<html>` once
 * the user picks a theme; until then DaisyUI's `light` is the baseline.
 */
const val DEFAULT_THEME = "light"

/**
 * The default interaction style for interactive examples. The
 * [interactionStyleSwitcher] allows the user to choose between htmx, Alpine.js,
 * and Datastar; the choice persists across navigation via localStorage.
 */
const val DEFAULT_INTERACTION_STYLE = "htmx"

/**
 * Every available interaction style offered by the [interactionStyleSwitcher].
 * Each maps to a library used in the docs' interactive examples (ADR-0005).
 */
val INTERACTION_STYLES = listOf("htmx", "alpine", "datastar")

/**
 * Every DaisyUI built-in theme, offered by the [themeSwitcher]. `input.css`
 * enables `themes: all`, so each of these compiles into `output.css` and can be
 * previewed live. Order matches DaisyUI's own theme list.
 */
val THEMES =
    listOf(
        "light",
        "dark",
        "cupcake",
        "bumblebee",
        "emerald",
        "corporate",
        "synthwave",
        "retro",
        "cyberpunk",
        "valentine",
        "halloween",
        "garden",
        "forest",
        "aqua",
        "lofi",
        "pastel",
        "fantasy",
        "wireframe",
        "black",
        "luxury",
        "dracula",
        "cmyk",
        "autumn",
        "business",
        "acid",
        "lemonade",
        "night",
        "coffee",
        "winter",
        "dim",
        "nord",
        "sunset",
        "caramellatte",
        "abyss",
        "silk",
    )

/**
 * Opens `<html data-theme="light" lang="en">`. The attributes are passed at tag
 * construction (not inside the block) because a streaming consumer writes the
 * open tag before the block runs, so attributes set afterwards would be too late.
 */
private fun <T> TagConsumer<T>.htmlDocument(block: HTML.() -> Unit): T =
    HTML(mapOf("data-theme" to DEFAULT_THEME, "lang" to "en"), this, namespace = null)
        .visitAndFinalize(this, block)

/**
 * Wraps page [content] in the shared document: the default `data-theme` on the
 * html element for DaisyUI, the compiled Tailwind stylesheet, and the sidebar
 * that highlights the [active] page (whose label is also the document title).
 * Returns a full HTML document string.
 */
fun layout(
    active: NavItem,
    content: FlowContent.() -> Unit,
): String =
    buildString {
        append("<!DOCTYPE html>")
        appendHTML(prettyPrint = false).htmlDocument {
            head {
                meta(charset = "utf-8")
                meta(name = "viewport", content = "width=device-width, initial-scale=1")
                title { +"Mosaik UI · ${active.label}" }
                preferenceRestoreScript()
                // Generated by the `buildCss` task (mosaik-gradle); served from resources/static.
                link(rel = "stylesheet", href = "/static/output.css")
                // Interactivity libraries for live previews (htmx, Alpine.js, Datastar)
                script(src = "https://unpkg.com/htmx.org@2.0.4") {}
                script(src = "https://unpkg.com/alpinejs@3.14.7/dist/cdn.min.js") { defer = true }
                script(src = "/static/vendor/datastar.js") { type = "module" }
                // Syntax highlighting for Kotlin code blocks.
                link(
                    rel = "stylesheet",
                    href = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/styles/github-dark.min.css",
                )
                script(src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js") {}
                script(src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/languages/kotlin.min.js") {}
                script {
                    unsafe {
                        +"hljs.highlightAll();"
                    }
                }
                // Kotlin/JS docs client bundle (generated at build time).
                script(src = "/static/mosaik-docs-client.js") {}
            }
            body(classes = "min-h-screen bg-base-100 text-base-content") {
                div("flex min-h-screen") {
                    sidebar(active.path)
                    main(classes = "flex-1 p-8 prose max-w-none") {
                        id = "main-content"
                        content()
                    }
                }
            }
        }
    }

/**
 * Renders just the page [content] without the full document shell. Used for
 * progressive shell navigation where the client fetches and swaps only the main
 * content area instead of reloading the entire page.
 */
fun partialContent(content: FlowContent.() -> Unit): String =
    buildString {
        appendHTML(prettyPrint = false).div("contents") { content() }
    }

/**
 * Left navigation listing Home, component pages, guide pages, the theme switcher,
 * and the interaction style switcher.
 */
private fun FlowContent.sidebar(activePath: String) {
    aside(classes = "w-64 shrink-0 bg-base-200 p-4") {
        h1("text-xl font-bold px-2 pb-4") { +"Mosaik UI" }
        mMenu("w-full") {
            mMenuItem(HOME.path, active = HOME.path == activePath) { +HOME.label }
            mMenuTitle { +"Components" }
            COMPONENTS.forEach { item ->
                mMenuItem(item.path, active = item.path == activePath) { +item.label }
            }
            mMenuTitle { +"Guides" }
            GUIDES.forEach { item ->
                mMenuItem(item.path, active = item.path == activePath) { +item.label }
            }
        }
        themeSwitcher()
        interactionStyleSwitcher()
    }
}

/**
 * A `<select>` in the sidebar that previews the page in any DaisyUI theme. On
 * change it sets `data-theme` on `<html>` and persists the choice to
 * localStorage; [themeRestoreScript] reapplies it on the next page load. This is
 * docs-only JavaScript — components remain CSS-only (see PRD #10).
 */
private fun FlowContent.themeSwitcher() {
    div("px-2 pt-6") {
        label("label text-xs opacity-70") {
            attributes["for"] = "theme-switcher"
            +"Theme"
        }
        mSelect(size = Size.Sm, classes = "w-full mt-1") {
            id = "theme-switcher"
            attributes["onchange"] =
                "document.documentElement.setAttribute('data-theme', this.value);" +
                "localStorage.setItem('mosaik-theme', this.value);"
            THEMES.forEach { theme ->
                option {
                    value = theme
                    +theme.replaceFirstChar { it.uppercase() }
                }
            }
        }
    }
}

/**
 * A `<select>` in the sidebar that lets users choose their preferred interaction
 * style for interactive examples (htmx, Alpine.js, or Datastar). On change it
 * persists the choice to localStorage and triggers interactivity tab groups to
 * switch to the selected style. This is docs-only JavaScript — components remain
 * CSS-only.
 */
private fun FlowContent.interactionStyleSwitcher() {
    div("px-2 pt-4") {
        label("label text-xs opacity-70") {
            attributes["for"] = "interaction-style-switcher"
            +"Interaction Style"
        }
        mSelect(size = Size.Sm, classes = "w-full mt-1") {
            id = "interaction-style-switcher"
            attributes["onchange"] =
                "document.documentElement.setAttribute('data-interaction-style', this.value);" +
                "localStorage.setItem('mosaik-interaction-style', this.value);" +
                "document.querySelectorAll('.tabs input[type=\"radio\"]').forEach(function(input) {" +
                "  if (input.getAttribute('data-interaction-style') === " +
                "localStorage.getItem('mosaik-interaction-style')) {" +
                "    input.checked = true;" +
                "  }" +
                "});"
            INTERACTION_STYLES.forEach { style ->
                option {
                    value = style
                    +when (style) {
                        "htmx" -> "htmx"
                        "alpine" -> "Alpine.js"
                        "datastar" -> "Datastar"
                        else -> style
                    }
                }
            }
        }
    }
}

/**
 * Applies localStorage-backed preferences before the stylesheet is loaded. This
 * prevents a post-render DaisyUI theme swap from causing a visible page reflow.
 */
private fun HEAD.preferenceRestoreScript() {
    script {
        unsafe {
            +
                """
                (function () {
                  var theme = localStorage.getItem('mosaik-theme');
                  if (theme) { document.documentElement.setAttribute('data-theme', theme); }
                  document.documentElement.dataset.interactionStyle =
                    localStorage.getItem('mosaik-interaction-style') || '$DEFAULT_INTERACTION_STYLE';
                })();
                """.trimIndent()
        }
    }
}
