package mosaik.docs

import kotlinx.html.*
import kotlinx.html.stream.appendHTML
import mosaik.ui.components.AlertVariant
import mosaik.ui.components.BadgeVariant
import mosaik.ui.components.Size
import mosaik.ui.components.Variant
import mosaik.ui.components.mAlert
import mosaik.ui.components.mBadge
import mosaik.ui.components.mButton
import mosaik.ui.components.mCard
import mosaik.ui.components.mCardActions
import mosaik.ui.components.mCardBody
import mosaik.ui.components.mCardTitle
import mosaik.ui.components.mNavbar
import mosaik.ui.components.mNavbarCenter
import mosaik.ui.components.mNavbarEnd
import mosaik.ui.components.mNavbarStart

/** A documentation page: the route it lives at, its sidebar label, and how it renders. */
data class NavItem(val path: String, val label: String, val render: () -> String)

/** The landing page. */
val HOME = NavItem("/", "Home", ::landingPage)

/** The Button documentation page. */
val BUTTON = NavItem("/components/button", "Button", ::buttonPage)

/** The Card documentation page. */
val CARD = NavItem("/components/card", "Card", ::cardPage)

/** The Navbar documentation page. */
val NAVBAR = NavItem("/components/navbar", "Navbar", ::navbarPage)

/** The Badge documentation page. */
val BADGE = NavItem("/components/badge", "Badge", ::badgePage)

/** The Alert documentation page. */
val ALERT = NavItem("/components/alert", "Alert", ::alertPage)

/**
 * Every component documentation page. Together with [HOME] this is the single
 * source of truth for the sidebar links and the routing table (see
 * [mosaik.docs.module]), so adding a component page is one [NavItem] plus its
 * renderer.
 */
val COMPONENTS = listOf(BUTTON, CARD, NAVBAR, BADGE, ALERT)

/**
 * The theme the server renders before any client-side preference is applied. The
 * [themeSwitcher] (and the restore script) override `data-theme` on `<html>` once
 * the user picks a theme; until then DaisyUI's `light` is the baseline.
 */
const val DEFAULT_THEME = "light"

/**
 * Every DaisyUI built-in theme, offered by the [themeSwitcher]. `input.css`
 * enables `themes: all`, so each of these compiles into `output.css` and can be
 * previewed live. Order matches DaisyUI's own theme list.
 */
val THEMES = listOf(
    "light", "dark", "cupcake", "bumblebee", "emerald", "corporate", "synthwave",
    "retro", "cyberpunk", "valentine", "halloween", "garden", "forest", "aqua",
    "lofi", "pastel", "fantasy", "wireframe", "black", "luxury", "dracula", "cmyk",
    "autumn", "business", "acid", "lemonade", "night", "coffee", "winter", "dim",
    "nord", "sunset", "caramellatte", "abyss", "silk",
)

/**
 * Opens `<html data-theme="light" lang="en">`. The attributes are passed at tag
 * construction (not inside the block) because a streaming consumer writes the
 * open tag before the block runs, so attributes set afterwards would be too late.
 */
private fun <T> TagConsumer<T>.htmlDocument(block: HTML.() -> Unit): T =
    HTML(mapOf("data-theme" to DEFAULT_THEME, "lang" to "en"), this, namespace = null)
        .visitAndFinalize(this, block)

/**
 * Wraps page [content] in the shared document: the default `data-theme` on the
 * html element for DaisyUI, the compiled Tailwind stylesheet, and the sidebar
 * that highlights the [active] page (whose label is also the document title).
 * Returns a full HTML document string.
 */
fun layout(active: NavItem, content: FlowContent.() -> Unit): String =
    buildString {
        append("<!DOCTYPE html>")
        appendHTML(prettyPrint = false).htmlDocument {
            head {
                meta(charset = "utf-8")
                meta(name = "viewport", content = "width=device-width, initial-scale=1")
                title { +"Mosaik UI · ${active.label}" }
                // Generated by the `buildCss` task (mosaik-gradle); served from resources/static.
                link(rel = "stylesheet", href = "/static/output.css")
            }
            body(classes = "min-h-screen bg-base-100 text-base-content") {
                div("flex min-h-screen") {
                    sidebar(active.path)
                    main(classes = "flex-1 p-8 prose max-w-none") { content() }
                }
                themeRestoreScript()
            }
        }
    }

/** Left navigation listing Home, every component page, and the theme switcher. */
private fun FlowContent.sidebar(activePath: String) {
    aside(classes = "w-64 shrink-0 bg-base-200 p-4") {
        h1("text-xl font-bold px-2 pb-4") { +"Mosaik UI" }
        ul("menu w-full") {
            navLink(HOME, activePath)
            COMPONENTS.forEach { navLink(it, activePath) }
        }
        themeSwitcher()
    }
}

private fun UL.navLink(item: NavItem, activePath: String) {
    li {
        // DaisyUI marks the current menu entry with `menu-active`.
        val active = if (item.path == activePath) "menu-active" else ""
        a(href = item.path, classes = active) { +item.label }
    }
}

/**
 * A `<select>` in the sidebar that previews the page in any DaisyUI theme. On
 * change it sets `data-theme` on `<html>` and persists the choice to
 * localStorage; [themeRestoreScript] reapplies it on the next page load. This is
 * docs-only JavaScript — components remain CSS-only (see PRD #10).
 */
private fun FlowContent.themeSwitcher() {
    div("px-2 pt-6") {
        label("label text-xs opacity-70") {
            attributes["for"] = "theme-switcher"
            +"Theme"
        }
        select(classes = "select select-sm select-bordered w-full mt-1") {
            id = "theme-switcher"
            attributes["onchange"] =
                "document.documentElement.setAttribute('data-theme', this.value);" +
                    "localStorage.setItem('mosaik-theme', this.value);"
            THEMES.forEach { theme ->
                option {
                    value = theme
                    +theme.replaceFirstChar { it.uppercase() }
                }
            }
        }
    }
}

/**
 * Reapplies the saved theme (if any) on load and syncs the [themeSwitcher] to the
 * active theme, so the dropdown reflects the previewed theme across navigation.
 */
private fun FlowContent.themeRestoreScript() {
    script {
        unsafe {
            +"""
            (function () {
              var saved = localStorage.getItem('mosaik-theme');
              if (saved) { document.documentElement.setAttribute('data-theme', saved); }
              var sel = document.getElementById('theme-switcher');
              if (sel) { sel.value = document.documentElement.getAttribute('data-theme'); }
            })();
            """.trimIndent()
        }
    }
}

// ---------------------------------------------------------------------------
// Page template helpers — every component page is built from these sections so
// the layout stays consistent (PRD #10, issue #11). Code examples are static
// strings here; there is no build-time extraction from component sources.
// ---------------------------------------------------------------------------

/** A row in an [apiReference] table: one component parameter. */
data class ApiParam(
    val name: String,
    val type: String,
    val default: String,
    val description: String,
)

/** The `./gradlew mosaikAdd` install command for [component]. */
private fun FlowContent.installSection(component: String) {
    h2 { +"Installation" }
    codeBlock("./gradlew mosaikAdd --component=$component")
}

/** A minimal Kotlin usage snippet under a "Basic usage" heading. */
private fun FlowContent.usageSection(code: String) {
    h2 { +"Basic usage" }
    codeBlock(code)
}

/** A fenced, monospaced code block. Text is escaped by kotlinx.html. */
private fun FlowContent.codeBlock(code: String) {
    pre("bg-base-200 rounded-box p-4 overflow-x-auto") {
        code { +code }
    }
}

/** The parameter reference table closing every component page. */
private fun FlowContent.apiReference(params: List<ApiParam>) {
    h2 { +"API reference" }
    div("overflow-x-auto") {
        table("table table-zebra") {
            thead {
                tr {
                    th { +"Parameter" }
                    th { +"Type" }
                    th { +"Default" }
                    th { +"Description" }
                }
            }
            tbody {
                params.forEach { p ->
                    tr {
                        td { code { +p.name } }
                        td { code { +p.type } }
                        td { code { +p.default } }
                        td { +p.description }
                    }
                }
            }
        }
    }
}

/** Landing page: a short intro and where to look next. */
fun landingPage(): String = layout(HOME) {
    h1 { +"Mosaik UI" }
    p { +"ShadCN-style components for Kotlin, Ktor and Gradle. Pick a component from the sidebar to see every variant rendered." }
    p {
        +"This app dogfoods "
        span("font-mono") { +"mosaik-components" }
        +" directly: if a page renders correctly, the component works."
    }
    p { +"Use the theme switcher in the sidebar to preview components in any DaisyUI theme." }
}

/**
 * Button page, following the five-section component template: title +
 * description, installation, basic usage, a variants/sizes showcase paired with
 * its Kotlin code, and the API reference table.
 */
fun buttonPage(): String = layout(BUTTON) {
    h1 { +"Button" }
    p {
        +"A button triggers an action or event — submitting a form, opening a dialog, "
        +"or navigating. "
        code { +"mButton" }
        +" is a thin wrapper over DaisyUI's "
        code { +"btn" }
        +" classes that takes its colour role and size as parameters and hands you "
        +"the raw kotlinx.html element, so any HTML attribute or library extension "
        +"(e.g. htmx) works natively (ADR-0003)."
    }

    installSection("button")

    usageSection(
        """
        import mosaik.ui.components.mButton
        import mosaik.ui.components.Variant
        import mosaik.ui.components.Size

        mButton(Variant.Primary, Size.Md) {
            +"Save"
        }
        """.trimIndent(),
    )

    section {
        h2 { +"Variants" }
        p {
            +"Every "
            code { +"Variant" }
            +" maps to a DaisyUI colour role."
        }
        div("flex flex-wrap gap-2 not-prose") {
            Variant.entries.forEach { v ->
                mButton(variant = v) { +v.name }
            }
        }
        codeBlock(
            """
            Variant.entries.forEach { v ->
                mButton(variant = v) { +v.name }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"Sizes" }
        p {
            +"Five "
            code { +"Size" }
            +" steps; "
            code { +"Size.Md" }
            +" is the unstyled baseline and renders no size class."
        }
        div("flex flex-wrap items-center gap-2 not-prose") {
            Size.entries.forEach { s ->
                mButton(variant = Variant.Primary, size = s) { +s.name }
            }
        }
        codeBlock(
            """
            Size.entries.forEach { s ->
                mButton(variant = Variant.Primary, size = s) { +s.name }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"Disabled" }
        div("flex flex-wrap gap-2 not-prose") {
            mButton(variant = Variant.Primary) { disabled = true; +"Disabled" }
        }
        codeBlock(
            """
            mButton(variant = Variant.Primary) {
                disabled = true
                +"Disabled"
            }
            """.trimIndent(),
        )
    }

    apiReference(
        listOf(
            ApiParam(
                "variant",
                "Variant",
                "Variant.Primary",
                "DaisyUI colour role: Primary, Secondary, Accent, Ghost, Link, Error, Success, Warning.",
            ),
            ApiParam(
                "size",
                "Size",
                "Size.Md",
                "Size step: Xs, Sm, Md, Lg, Xl. Md is the baseline and adds no class.",
            ),
            ApiParam(
                "classes",
                "String?",
                "null",
                "Extra CSS classes appended after the generated btn classes.",
            ),
            ApiParam(
                "block",
                "BUTTON.() -> Unit",
                "{}",
                "Receiver block on the raw kotlinx.html BUTTON element — set text, attributes, or library extensions.",
            ),
        ),
    )
}

/**
 * Card page, following the five-section component template: title +
 * description, installation, basic usage showing the sub-component nesting,
 * a showcase of card compositions (plain, with actions, with image) paired with
 * their Kotlin code, and an API reference covering the card and its
 * sub-components. Card has no variants or sizes — it is a layout container.
 */
fun cardPage(): String = layout(CARD) {
    h1 { +"Card" }
    p {
        +"A card groups related content and actions into a single surface — an "
        +"image, a title, body text, and a row of buttons. "
        code { +"mCard" }
        +" wraps DaisyUI's "
        code { +"card" }
        +" classes and, unlike Button or Badge, takes no colour role or size: it "
        +"is a layout container styled by the utility classes you pass (e.g. "
        code { +"bg-base-100 shadow-sm" }
        +"). It hands you the raw kotlinx.html element, so any HTML attribute or "
        +"library extension (e.g. htmx) works natively (ADR-0003)."
    }
    p {
        +"A card composes from sub-components scoped to its receiver: "
        code { +"mCardBody" }
        +" for the padded "
        code { +"card-body" }
        +" container, and inside it "
        code { +"mCardTitle" }
        +" (an "
        code { +"<h2>" }
        +" with "
        code { +"card-title" }
        +") and "
        code { +"mCardActions" }
        +" for a "
        code { +"card-actions" }
        +" button row. An image is a plain "
        code { +"figure" }
        +" — no wrapper needed."
    }

    installSection("card")

    usageSection(
        """
        import mosaik.ui.components.mCard
        import mosaik.ui.components.mCardBody
        import mosaik.ui.components.mCardTitle
        import mosaik.ui.components.mCardActions
        import mosaik.ui.components.mButton
        import mosaik.ui.components.Variant

        mCard("w-96 bg-base-100 shadow-sm") {
            mCardBody {
                mCardTitle { +"Shoes!" }
                p { +"If a dog chews shoes whose shoes does he choose?" }
                mCardActions("justify-end") {
                    mButton(Variant.Primary) { +"Buy Now" }
                }
            }
        }
        """.trimIndent(),
    )

    section {
        h2 { +"Basic card" }
        p { +"A card with a title and body text." }
        div("not-prose") {
            mCard("w-96 bg-base-100 shadow-sm") {
                mCardBody {
                    mCardTitle { +"Card title" }
                    p { +"A card with a title and a short description below it." }
                }
            }
        }
        codeBlock(
            """
            mCard("w-96 bg-base-100 shadow-sm") {
                mCardBody {
                    mCardTitle { +"Card title" }
                    p { +"A card with a title and a short description below it." }
                }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"With actions" }
        p {
            +"A "
            code { +"card-actions" }
            +" row holds buttons or controls, usually right-aligned with "
            code { +"justify-end" }
            +"."
        }
        div("not-prose") {
            mCard("w-96 bg-base-100 shadow-sm") {
                mCardBody {
                    mCardTitle { +"Buy these shoes" }
                    p { +"If a dog chews shoes whose shoes does he choose?" }
                    mCardActions("justify-end") {
                        mButton(Variant.Primary) { +"Buy Now" }
                    }
                }
            }
        }
        codeBlock(
            """
            mCard("w-96 bg-base-100 shadow-sm") {
                mCardBody {
                    mCardTitle { +"Buy these shoes" }
                    p { +"If a dog chews shoes whose shoes does he choose?" }
                    mCardActions("justify-end") {
                        mButton(Variant.Primary) { +"Buy Now" }
                    }
                }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"With image" }
        p {
            +"Place a "
            code { +"figure" }
            +" before the body for DaisyUI's image card layout."
        }
        div("not-prose") {
            mCard("w-96 bg-base-100 shadow-sm") {
                figure {
                    img(src = "https://placehold.co/384x192", alt = "Placeholder")
                }
                mCardBody {
                    mCardTitle { +"Image card" }
                    p { +"An image sits in a figure above the body." }
                }
            }
        }
        codeBlock(
            """
            mCard("w-96 bg-base-100 shadow-sm") {
                figure {
                    img(src = "/shoes.jpg", alt = "Shoes")
                }
                mCardBody {
                    mCardTitle { +"Image card" }
                    p { +"An image sits in a figure above the body." }
                }
            }
            """.trimIndent(),
        )
    }

    apiReference(
        listOf(
            ApiParam(
                "classes",
                "String?",
                "null",
                "Extra CSS classes appended after the generated card classes (e.g. bg-base-100 shadow-sm w-96).",
            ),
            ApiParam(
                "block",
                "DIV.() -> Unit",
                "{}",
                "Receiver block on the raw kotlinx.html DIV element — nest mCardBody, a figure, attributes, or library extensions.",
            ),
        ),
    )

    section {
        h2 { +"Sub-components" }
        p {
            +"Each sub-component is an extension on the card's "
            code { +"DIV" }
            +" receiver, so it autocompletes inside the card block. All take the "
            +"same optional "
            code { +"classes" }
            +" parameter and live in "
            code { +"Card.kt" }
            +"."
        }
        div("overflow-x-auto") {
            table("table table-zebra") {
                thead {
                    tr {
                        th { +"Function" }
                        th { +"Element" }
                        th { +"Class" }
                        th { +"Description" }
                    }
                }
                tbody {
                    tr {
                        td { code { +"mCardBody" } }
                        td { code { +"DIV" } }
                        td { code { +"card-body" } }
                        td { +"The padded container for the title, text, and actions." }
                    }
                    tr {
                        td { code { +"mCardTitle" } }
                        td { code { +"H2" } }
                        td { code { +"card-title" } }
                        td { +"The card heading, rendered as an h2. Called inside mCardBody." }
                    }
                    tr {
                        td { code { +"mCardActions" } }
                        td { code { +"DIV" } }
                        td { code { +"card-actions" } }
                        td { +"A row for buttons or controls, usually with justify-end. Called inside mCardBody." }
                    }
                }
            }
        }
    }
}

/**
 * Navbar page, following the five-section component template: title +
 * description, installation, basic usage showing the slot pattern, a showcase of
 * slot combinations (start+end, centred title, all three slots) paired with their
 * Kotlin code, and an API reference covering the navbar and its slot
 * sub-components. Navbar has no variants or sizes — it is a layout container.
 */
fun navbarPage(): String = layout(NAVBAR) {
    h1 { +"Navbar" }
    p {
        +"A navbar is the bar at the top of a page that holds the brand, navigation "
        +"links, and actions. "
        code { +"mNavbar" }
        +" wraps DaisyUI's "
        code { +"navbar" }
        +" classes and, like Card, takes no colour role or size: it is a layout "
        +"container styled by the utility classes you pass (e.g. "
        code { +"bg-base-100 shadow-sm" }
        +"). It hands you the raw kotlinx.html element, so any HTML attribute or "
        +"library extension (e.g. htmx) works natively (ADR-0003)."
    }
    p {
        +"A navbar composes from three slot sub-components scoped to its receiver, "
        +"mirroring DaisyUI's layout: "
        code { +"mNavbarStart" }
        +" for the leading "
        code { +"navbar-start" }
        +" section (brand or menu), "
        code { +"mNavbarCenter" }
        +" for the centred "
        code { +"navbar-center" }
        +" section (title or links), and "
        code { +"mNavbarEnd" }
        +" for the trailing "
        code { +"navbar-end" }
        +" section (actions). Use only the slots you need."
    }

    installSection("navbar")

    usageSection(
        """
        import mosaik.ui.components.mNavbar
        import mosaik.ui.components.mNavbarStart
        import mosaik.ui.components.mNavbarEnd
        import mosaik.ui.components.mButton
        import mosaik.ui.components.Variant

        mNavbar("bg-base-100 shadow-sm") {
            mNavbarStart {
                a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
            }
            mNavbarEnd {
                mButton(Variant.Primary) { +"Sign up" }
            }
        }
        """.trimIndent(),
    )

    section {
        h2 { +"Start and end" }
        p {
            +"The most common navbar: a brand in "
            code { +"navbar-start" }
            +" and an action in "
            code { +"navbar-end" }
            +"."
        }
        div("not-prose") {
            mNavbar("bg-base-100 shadow-sm rounded-box") {
                mNavbarStart {
                    a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
                }
                mNavbarEnd {
                    mButton(Variant.Primary) { +"Sign up" }
                }
            }
        }
        codeBlock(
            """
            mNavbar("bg-base-100 shadow-sm") {
                mNavbarStart {
                    a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
                }
                mNavbarEnd {
                    mButton(Variant.Primary) { +"Sign up" }
                }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"Centred title" }
        p {
            +"A single "
            code { +"navbar-center" }
            +" slot centres the content."
        }
        div("not-prose") {
            mNavbar("bg-base-100 shadow-sm rounded-box") {
                mNavbarCenter {
                    a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
                }
            }
        }
        codeBlock(
            """
            mNavbar("bg-base-100 shadow-sm") {
                mNavbarCenter {
                    a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
                }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"All three slots" }
        p {
            +"Brand, centred links, and a trailing action together — the full "
            +"three-slot layout."
        }
        div("not-prose") {
            mNavbar("bg-base-100 shadow-sm rounded-box") {
                mNavbarStart {
                    a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
                }
                mNavbarCenter("hidden lg:flex") {
                    a(classes = "btn btn-ghost") { +"Docs" }
                }
                mNavbarEnd {
                    mButton(Variant.Primary) { +"Sign up" }
                }
            }
        }
        codeBlock(
            """
            mNavbar("bg-base-100 shadow-sm") {
                mNavbarStart {
                    a(classes = "btn btn-ghost text-xl") { +"Mosaik" }
                }
                mNavbarCenter("hidden lg:flex") {
                    a(classes = "btn btn-ghost") { +"Docs" }
                }
                mNavbarEnd {
                    mButton(Variant.Primary) { +"Sign up" }
                }
            }
            """.trimIndent(),
        )
    }

    apiReference(
        listOf(
            ApiParam(
                "classes",
                "String?",
                "null",
                "Extra CSS classes appended after the generated navbar classes (e.g. bg-base-100 shadow-sm).",
            ),
            ApiParam(
                "block",
                "DIV.() -> Unit",
                "{}",
                "Receiver block on the raw kotlinx.html DIV element — nest the slot sub-components, attributes, or library extensions.",
            ),
        ),
    )

    section {
        h2 { +"Sub-components" }
        p {
            +"Each slot is an extension on the navbar's "
            code { +"DIV" }
            +" receiver, so it autocompletes inside the navbar block. All take the "
            +"same optional "
            code { +"classes" }
            +" parameter and live in "
            code { +"Navbar.kt" }
            +"."
        }
        div("overflow-x-auto") {
            table("table table-zebra") {
                thead {
                    tr {
                        th { +"Function" }
                        th { +"Element" }
                        th { +"Class" }
                        th { +"Description" }
                    }
                }
                tbody {
                    tr {
                        td { code { +"mNavbarStart" } }
                        td { code { +"DIV" } }
                        td { code { +"navbar-start" } }
                        td { +"The leading section, typically the brand or a dropdown menu." }
                    }
                    tr {
                        td { code { +"mNavbarCenter" } }
                        td { code { +"DIV" } }
                        td { code { +"navbar-center" } }
                        td { +"The centred section, typically the title or primary navigation links." }
                    }
                    tr {
                        td { code { +"mNavbarEnd" } }
                        td { code { +"DIV" } }
                        td { code { +"navbar-end" } }
                        td { +"The trailing section, typically actions such as buttons or an avatar." }
                    }
                }
            }
        }
    }
}

/**
 * Badge page, following the five-section component template: title +
 * description, installation, basic usage, a variants/sizes showcase paired with
 * its Kotlin code, and the API reference table.
 */
fun badgePage(): String = layout(BADGE) {
    h1 { +"Badge" }
    p {
        +"A badge is a small inline label for status, counts, or categories — "
        +"sitting beside text, in a list, or on the corner of another element. "
        code { +"mBadge" }
        +" wraps DaisyUI's "
        code { +"badge" }
        +" classes and takes its colour role and size as parameters, handing you "
        +"the raw kotlinx.html element so any HTML attribute or library extension "
        +"(e.g. htmx) works natively (ADR-0003)."
    }
    p {
        +"Unlike Button, Badge declares its own "
        code { +"BadgeVariant" }
        +" enum (ADR-0004): DaisyUI's badge palette adds "
        code { +"info" }
        +", "
        code { +"neutral" }
        +", and "
        code { +"outline" }
        +", so the shared "
        code { +"Variant" }
        +" wouldn't fit."
    }

    installSection("badge")

    usageSection(
        """
        import mosaik.ui.components.mBadge
        import mosaik.ui.components.BadgeVariant
        import mosaik.ui.components.Size

        mBadge(BadgeVariant.Success, Size.Sm) {
            +"Active"
        }
        """.trimIndent(),
    )

    section {
        h2 { +"Variants" }
        p {
            +"Every "
            code { +"BadgeVariant" }
            +" maps to a DaisyUI badge colour role."
        }
        div("flex flex-wrap gap-2 not-prose") {
            BadgeVariant.entries.forEach { v ->
                mBadge(variant = v) { +v.name }
            }
        }
        codeBlock(
            """
            BadgeVariant.entries.forEach { v ->
                mBadge(variant = v) { +v.name }
            }
            """.trimIndent(),
        )
    }

    section {
        h2 { +"Sizes" }
        p {
            +"Five "
            code { +"Size" }
            +" steps; "
            code { +"Size.Md" }
            +" is the unstyled baseline and renders no size class."
        }
        div("flex flex-wrap items-center gap-2 not-prose") {
            Size.entries.forEach { s ->
                mBadge(variant = BadgeVariant.Primary, size = s) { +s.name }
            }
        }
        codeBlock(
            """
            Size.entries.forEach { s ->
                mBadge(variant = BadgeVariant.Primary, size = s) { +s.name }
            }
            """.trimIndent(),
        )
    }

    apiReference(
        listOf(
            ApiParam(
                "variant",
                "BadgeVariant",
                "BadgeVariant.Primary",
                "DaisyUI colour role: Primary, Secondary, Accent, Ghost, Info, Success, Warning, Error, Neutral, Outline.",
            ),
            ApiParam(
                "size",
                "Size",
                "Size.Md",
                "Size step: Xs, Sm, Md, Lg, Xl. Md is the baseline and adds no class.",
            ),
            ApiParam(
                "classes",
                "String?",
                "null",
                "Extra CSS classes appended after the generated badge classes.",
            ),
            ApiParam(
                "block",
                "SPAN.() -> Unit",
                "{}",
                "Receiver block on the raw kotlinx.html SPAN element — set text, attributes, or library extensions.",
            ),
        ),
    )
}

/**
 * Alert page, following the five-section component template: title +
 * description, installation, basic usage, a variants showcase paired with its
 * Kotlin code, and the API reference table. Alert has no size showcase —
 * DaisyUI alerts have no size modifiers.
 */
fun alertPage(): String = layout(ALERT) {
    h1 { +"Alert" }
    p {
        +"An alert conveys a feedback message — informational, success, warning, "
        +"or error — drawing attention without interrupting the flow. "
        code { +"mAlert" }
        +" wraps DaisyUI's "
        code { +"alert" }
        +" classes and takes its colour role as a parameter, handing you the raw "
        +"kotlinx.html element so any HTML attribute or library extension "
        +"(e.g. htmx) works natively (ADR-0003)."
    }
    p {
        +"Like Badge, Alert declares its own "
        code { +"AlertVariant" }
        +" enum (ADR-0004), scoped to the four roles DaisyUI alerts render: "
        code { +"info" }
        +", "
        code { +"success" }
        +", "
        code { +"warning" }
        +", and "
        code { +"error" }
        +". It carries "
        code { +"role=\"alert\"" }
        +" by default for assistive tech, and takes no "
        code { +"Size" }
        +" — alerts have no size modifiers."
    }

    installSection("alert")

    usageSection(
        """
        import mosaik.ui.components.mAlert
        import mosaik.ui.components.AlertVariant

        mAlert(AlertVariant.Success) {
            +"Your changes have been saved."
        }
        """.trimIndent(),
    )

    section {
        h2 { +"Variants" }
        p {
            +"Every "
            code { +"AlertVariant" }
            +" maps to a DaisyUI alert colour role."
        }
        div("flex flex-col gap-2 not-prose") {
            AlertVariant.entries.forEach { v ->
                mAlert(variant = v) { +v.name }
            }
        }
        codeBlock(
            """
            AlertVariant.entries.forEach { v ->
                mAlert(variant = v) { +v.name }
            }
            """.trimIndent(),
        )
    }

    apiReference(
        listOf(
            ApiParam(
                "variant",
                "AlertVariant",
                "AlertVariant.Info",
                "DaisyUI colour role: Info, Success, Warning, Error.",
            ),
            ApiParam(
                "classes",
                "String?",
                "null",
                "Extra CSS classes appended after the generated alert classes.",
            ),
            ApiParam(
                "block",
                "DIV.() -> Unit",
                "{}",
                "Receiver block on the raw kotlinx.html DIV element — set text, attributes, or library extensions. Runs after role=\"alert\" is set, so it can override the role.",
            ),
        ),
    )
}
