package mosaik.docs

import kotlinx.html.*
import kotlinx.html.stream.appendHTML
import mosaik.ui.components.Size
import mosaik.ui.components.Variant
import mosaik.ui.components.mButton

/** A documentation page: the route it lives at, its sidebar label, and how it renders. */
data class NavItem(val path: String, val label: String, val render: () -> String)

/** The landing page. */
val HOME = NavItem("/", "Home", ::landingPage)

/** The Button documentation page. */
val BUTTON = NavItem("/components/button", "Button", ::buttonPage)

/**
 * Every component documentation page. Together with [HOME] this is the single
 * source of truth for the sidebar links and the routing table (see
 * [mosaik.docs.module]), so adding a component page is one [NavItem] plus its
 * renderer.
 */
val COMPONENTS = listOf(BUTTON)

/**
 * Opens `<html data-theme="light" lang="en">`. The attributes are passed at tag
 * construction (not inside the block) because a streaming consumer writes the
 * open tag before the block runs, so attributes set afterwards would be too late.
 */
private fun <T> TagConsumer<T>.htmlDocument(block: HTML.() -> Unit): T =
    HTML(mapOf("data-theme" to "light", "lang" to "en"), this, namespace = null)
        .visitAndFinalize(this, block)

/**
 * Wraps page [content] in the shared document: `data-theme="light"` on the html
 * element for DaisyUI, the compiled Tailwind stylesheet, and the sidebar that
 * highlights the [active] page (whose label is also the document title). Returns
 * a full HTML document string.
 */
fun layout(active: NavItem, content: FlowContent.() -> Unit): String =
    buildString {
        append("<!DOCTYPE html>")
        appendHTML(prettyPrint = false).htmlDocument {
            head {
                meta(charset = "utf-8")
                meta(name = "viewport", content = "width=device-width, initial-scale=1")
                title { +"Mosaik UI · ${active.label}" }
                // Generated by the `buildCss` task (mosaik-gradle); served from resources/static.
                link(rel = "stylesheet", href = "/static/output.css")
            }
            body(classes = "min-h-screen bg-base-100 text-base-content") {
                div("flex min-h-screen") {
                    sidebar(active.path)
                    main(classes = "flex-1 p-8 prose max-w-none") { content() }
                }
            }
        }
    }

/** Left navigation listing Home and every component page. */
private fun FlowContent.sidebar(activePath: String) {
    aside(classes = "w-64 shrink-0 bg-base-200 p-4") {
        h1("text-xl font-bold px-2 pb-4") { +"Mosaik UI" }
        ul("menu w-full") {
            navLink(HOME, activePath)
            COMPONENTS.forEach { navLink(it, activePath) }
        }
    }
}

private fun UL.navLink(item: NavItem, activePath: String) {
    li {
        // DaisyUI marks the current menu entry with `menu-active`.
        val active = if (item.path == activePath) "menu-active" else ""
        a(href = item.path, classes = active) { +item.label }
    }
}

/** Landing page: a short intro and where to look next. */
fun landingPage(): String = layout(HOME) {
    h1 { +"Mosaik UI" }
    p { +"ShadCN-style components for Kotlin, Ktor and Gradle. Pick a component from the sidebar to see every variant rendered." }
    p {
        +"This app dogfoods "
        span("font-mono") { +"mosaik-components" }
        +" directly: if a page renders correctly, the component works."
    }
}

/** Button page: every variant, every size, and the disabled state, each labelled. */
fun buttonPage(): String = layout(BUTTON) {
    h1 { +"Button" }
    p { +"A DaisyUI button rendered via mButton {}." }

    section {
        h2 { +"Variants" }
        div("flex flex-wrap gap-2") {
            Variant.entries.forEach { v ->
                mButton(variant = v) { +v.name }
            }
        }
    }

    section {
        h2 { +"Sizes" }
        div("flex flex-wrap items-center gap-2") {
            Size.entries.forEach { s ->
                mButton(variant = Variant.Primary, size = s) { +s.name }
            }
        }
    }

    section {
        h2 { +"Disabled" }
        div("flex flex-wrap gap-2") {
            mButton(variant = Variant.Primary) { disabled = true; +"Disabled" }
        }
    }
}
