package dev.jwillert.mosaik.core

import java.io.File

data class Finding(
    val file: File,
    val line: Int,
    val token: String,
    val suggestedComponent: String?,
)

object DaisyUiTokenScanner {
    private val DAISYUI_TOKENS =
        setOf(
            // Components
            "alert",
            "artboard",
            "avatar",
            "badge",
            "breadcrumbs",
            "btn",
            "card",
            "carousel",
            "chat",
            "checkbox",
            "collapse",
            "countdown",
            "diff",
            "divider",
            "drawer",
            "dropdown",
            "file-input",
            "footer",
            "hero",
            "indicator",
            "input",
            "join",
            "kbd",
            "link",
            "loading",
            "mask",
            "menu",
            "mockup-browser",
            "mockup-code",
            "mockup-phone",
            "mockup-window",
            "modal",
            "navbar",
            "progress",
            "radial-progress",
            "radio",
            "range",
            "rating",
            "select",
            "skeleton",
            "stack",
            "stat",
            "steps",
            "swap",
            "tab",
            "table",
            "textarea",
            "timeline",
            "toast",
            "toggle",
            "tooltip",
            // Component-specific modifiers and sub-parts
            "alert-info",
            "alert-success",
            "alert-warning",
            "alert-error",
            "avatar-group",
            "badge-primary",
            "badge-secondary",
            "badge-accent",
            "badge-ghost",
            "badge-outline",
            "badge-lg",
            "badge-md",
            "badge-sm",
            "badge-xs",
            "btn-primary",
            "btn-secondary",
            "btn-accent",
            "btn-info",
            "btn-success",
            "btn-warning",
            "btn-error",
            "btn-ghost",
            "btn-link",
            "btn-outline",
            "btn-active",
            "btn-disabled",
            "btn-block",
            "btn-circle",
            "btn-square",
            "btn-wide",
            "btn-lg",
            "btn-md",
            "btn-sm",
            "btn-xs",
            "card-body",
            "card-title",
            "card-actions",
            "card-bordered",
            "card-compact",
            "card-normal",
            "card-side",
            "carousel-item",
            "carousel-center",
            "carousel-end",
            "chat-start",
            "chat-end",
            "chat-image",
            "chat-header",
            "chat-footer",
            "chat-bubble",
            "collapse-title",
            "collapse-content",
            "collapse-arrow",
            "collapse-plus",
            "collapse-open",
            "collapse-close",
            "drawer-toggle",
            "drawer-content",
            "drawer-side",
            "drawer-overlay",
            "drawer-open",
            "drawer-end",
            "dropdown-content",
            "dropdown-top",
            "dropdown-bottom",
            "dropdown-left",
            "dropdown-right",
            "dropdown-end",
            "dropdown-hover",
            "dropdown-open",
            "footer-title",
            "footer-center",
            "hero-content",
            "hero-overlay",
            "indicator-item",
            "indicator-start",
            "indicator-center",
            "indicator-end",
            "indicator-top",
            "indicator-middle",
            "indicator-bottom",
            "input-bordered",
            "input-ghost",
            "input-primary",
            "input-secondary",
            "input-accent",
            "input-info",
            "input-success",
            "input-warning",
            "input-error",
            "input-lg",
            "input-md",
            "input-sm",
            "input-xs",
            "join-item",
            "join-vertical",
            "join-horizontal",
            "loading-spinner",
            "loading-dots",
            "loading-ring",
            "loading-ball",
            "loading-bars",
            "loading-infinity",
            "loading-lg",
            "loading-md",
            "loading-sm",
            "loading-xs",
            "menu-title",
            "menu-dropdown",
            "menu-dropdown-show",
            "menu-active",
            "modal-box",
            "modal-action",
            "modal-backdrop",
            "modal-toggle",
            "modal-open",
            "modal-top",
            "modal-middle",
            "modal-bottom",
            "navbar-start",
            "navbar-center",
            "navbar-end",
            "select-bordered",
            "select-ghost",
            "select-primary",
            "select-secondary",
            "select-accent",
            "select-info",
            "select-success",
            "select-warning",
            "select-error",
            "select-lg",
            "select-md",
            "select-sm",
            "select-xs",
            "stat-title",
            "stat-value",
            "stat-desc",
            "stat-figure",
            "stat-actions",
            "steps-vertical",
            "steps-horizontal",
            "step",
            "step-primary",
            "step-secondary",
            "step-accent",
            "step-info",
            "step-success",
            "step-warning",
            "step-error",
            "tab-active",
            "tab-disabled",
            "tab-lifted",
            "tab-bordered",
            "tab-lg",
            "tab-md",
            "tab-sm",
            "tab-xs",
            "table-zebra",
            "table-pin-rows",
            "table-pin-cols",
            "table-xs",
            "table-sm",
            "table-md",
            "table-lg",
            "textarea-bordered",
            "textarea-ghost",
            "textarea-primary",
            "textarea-secondary",
            "textarea-accent",
            "textarea-info",
            "textarea-success",
            "textarea-warning",
            "textarea-error",
            "textarea-lg",
            "textarea-md",
            "textarea-sm",
            "textarea-xs",
            "timeline-start",
            "timeline-middle",
            "timeline-end",
            "timeline-box",
            "toast-top",
            "toast-bottom",
            "toast-center",
            "toast-start",
            "toast-end",
            "toggle-primary",
            "toggle-secondary",
            "toggle-accent",
            "toggle-success",
            "toggle-warning",
            "toggle-info",
            "toggle-error",
            "toggle-lg",
            "toggle-md",
            "toggle-sm",
            "toggle-xs",
        )

    private val TOKEN_TO_COMPONENT =
        mapOf(
            "alert" to "Alert",
            "alert-info" to "Alert",
            "alert-success" to "Alert",
            "alert-warning" to "Alert",
            "alert-error" to "Alert",
            "btn" to "Button",
            "btn-primary" to "Button",
            "btn-secondary" to "Button",
            "btn-accent" to "Button",
            "btn-info" to "Button",
            "btn-success" to "Button",
            "btn-warning" to "Button",
            "btn-error" to "Button",
            "btn-ghost" to "Button",
            "btn-link" to "Button",
            "btn-outline" to "Button",
            "btn-active" to "Button",
            "btn-disabled" to "Button",
            "btn-block" to "Button",
            "btn-circle" to "Button",
            "btn-square" to "Button",
            "btn-wide" to "Button",
            "btn-lg" to "Button",
            "btn-md" to "Button",
            "btn-sm" to "Button",
            "btn-xs" to "Button",
            "card" to "Card",
            "card-body" to "Card",
            "card-title" to "Card",
            "card-actions" to "Card",
            "card-bordered" to "Card",
            "card-compact" to "Card",
            "card-normal" to "Card",
            "card-side" to "Card",
            "footer" to "Footer",
            "footer-title" to "Footer",
            "footer-center" to "Footer",
            "navbar" to "Navbar",
            "navbar-start" to "Navbar",
            "navbar-center" to "Navbar",
            "navbar-end" to "Navbar",
            "table" to "Table",
            "table-zebra" to "Table",
            "table-pin-rows" to "Table",
            "table-pin-cols" to "Table",
            "table-xs" to "Table",
            "table-sm" to "Table",
            "table-md" to "Table",
            "table-lg" to "Table",
        )

    fun scan(rootDir: File): List<Finding> {
        val findings = mutableListOf<Finding>()

        rootDir.walkTopDown().forEach { file ->
            if (file.isFile && file.extension == "kt" && !isAllowlisted(file)) {
                scanFile(file, findings)
            }
        }

        return findings.sortedWith(
            compareBy({ it.file.path }, { it.line }, { it.token }),
        )
    }

    private fun isAllowlisted(file: File): Boolean {
        val path = file.path
        return path.contains("mosaik/ui/components")
    }

    private fun scanFile(
        file: File,
        findings: MutableList<Finding>,
    ) {
        val lines = file.readLines()
        lines.forEachIndexed { index, line ->
            val tokens = extractClassTokens(line)
            tokens.forEach { token ->
                if (DAISYUI_TOKENS.contains(token)) {
                    findings.add(
                        Finding(
                            file = file,
                            line = index + 1,
                            token = token,
                            suggestedComponent = TOKEN_TO_COMPONENT[token],
                        ),
                    )
                }
            }
        }
    }

    private fun extractClassTokens(line: String): List<String> {
        val tokens = mutableListOf<String>()

        // Match class attribute strings like: classes = "btn btn-primary"
        // or direct class strings like: h6("footer-title")
        val classPatterns =
            listOf(
                """classes\s*=\s*"([^"]+)"""".toRegex(),
                """classes\s*=\s*buildClasses\([^)]*"([^"]+)"""".toRegex(),
                """\("([^"]+)"\)\s*\{""".toRegex(),
                """<[a-z]+\s+class="([^"]+)"""".toRegex(),
            )

        classPatterns.forEach { pattern ->
            pattern.findAll(line).forEach { match ->
                val classString = match.groupValues[1]
                tokens.addAll(classString.split("""\s+""".toRegex()).filter { it.isNotBlank() })
            }
        }

        return tokens
    }
}
